services:
  - type: web
    name: hngstagezero
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/HNGStageZero-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
